### ISSUE TITLE
WebService cannot get launched with python 3.10

### ISSUE THREAD

**Issue by shengyfu** [MusicAsLanguage/webservice#23]
WebService cannot get launched with python 3.10

This is the error log:

from flask_bcrypt import Bcrypt
bcrypt is required to use Flask-Bcrypt
Traceback (most recent call last):
File "", line 1, in
File "E:\GitHub\MusicAsLanguage\WebService.venv\lib\site-packages\flask_bcrypt.py", line 27, in
raise e
File "E:\GitHub\MusicAsLanguage\WebService.venv\lib\site-packages\flask_bcrypt.py", line 24, in
import bcrypt
File "E:\GitHub\MusicAsLanguage\WebService.venv\lib\site-packages\bcrypt_init_.py", line 25, in
from . import _bcrypt # type: ignore
ModuleNotFoundError: No module named '_cffi_backend'

**Comment by shengyfu** [comment]
Closing this as a duplicate to https://github.com/MusicAsLanguage/webservice/issues/24
